logo: M.A.Ulfat7.jpg
theme: jekyll-theme-modernist
description: "Data Analyst Portfolio"

# Optional — customize more below:
author:
  name: "Muhammad Asamullah Ulfat"
  avatar: "assets/profile.jpg" 
