logo: M.A.Ulfat7.jpg
theme: jekyll-theme-minimal
description: "Data Analyst Portfolio"
url: "https://asamullahulfat.github.io" # your GitHub Pages URL
baseurl: "" # leave empty unless it's a project site

# Optional — customize more below:
author:
  name: "Muhammad Asamullah Ulfat"
  avatar: "assets/profile.jpg" 
